Repository DeveloperAcademy-POSTECH/MC3_Team10_NoonMoa, pull requests merged in 2023-07, with the labels that each got.

#20 Asset/#19 : 추가 OnboadingView 내 이미지
  NoonMoaApt/Assets.xcassets/OnboardingImage/Contents.json
  NoonMoaApt/Assets.xcassets/OnboardingImage/onboarding1.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/OnboardingImage/onboarding1.imageset/onboarding1.png
  NoonMoaApt/Assets.xcassets/OnboardingImage/onboarding2.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/OnboardingImage/onboarding2.imageset/onboarding2.png
  NoonMoaApt/Assets.xcassets/OnboardingImage/onboarding3.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/OnboardingImage/onboarding3.imageset/onboarding3.png
Labels: Asset

#23 [Feat] 추가 CalendarView GUI 작업 #7
  NoonMoaApt/Assets.xcassets/LargeStamp_cloudyDay.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/LargeStamp_cloudyDay.imageset/LargeStamp_cloudyDay.png
  NoonMoaApt/Assets.xcassets/LargeStamp_rainyDay.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/LargeStamp_rainyDay.imageset/LargeStamp_rainyDay.png
  NoonMoaApt/Assets.xcassets/LargeStamp_snowyDay.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/LargeStamp_snowyDay.imageset/LargeStamp_snowyDay.png
  NoonMoaApt/Assets.xcassets/LargeStamp_thunder.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/LargeStamp_thunder.imageset/LargeStamp_thunder.png
  NoonMoaApt/Calendar/View/CalendarDayView.swift
  NoonMoaApt/Calendar/View/CalendarMonthView.swift
  NoonMoaApt/View/CalendarScene/StampLargeView.swift
Labels: Feat, UI

#25 [Feat] 추가 CalendarView GUI 작업 #7 #1
  NoonMoaApt/Assets.xcassets/calendar_selected.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/calendar_selected.imageset/calendar_selected.png
  NoonMoaApt/Assets.xcassets/calendar_unselected.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/calendar_unselected.imageset/calendar_unselected.png
  NoonMoaApt/Assets.xcassets/settings_selected.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/settings_selected.imageset/settings_selected.png
  NoonMoaApt/Assets.xcassets/settings_unselected.imageset/Contents.json
  NoonMoaApt/Assets.xcassets/settings_unselected.imageset/settings_unselected.png
  NoonMoaApt/Calendar/View/CalendarMonthView.swift
  NoonMoaApt/View/AptView.swift
Labels: Feat, UI

#26 Feat/#13 구현 Push Notification 관련
  NoonMoaApt.xcodeproj/project.pbxproj
  NoonMoaApt.xcodeproj/project.xcworkspace/xcuserdata/kimpepe.xcuserdatad/UserInterfaceState.xcuserstate
  NoonMoaApt/Model/AptViewModel.swift
  NoonMoaApt/Model/AttendanceCompletedViewModel.swift
  NoonMoaApt/Model/DummyData.swift
  NoonMoaApt/Model/FirebaseModel.swift
  NoonMoaApt/Model/LoginViewModel.swift
  NoonMoaApt/Model/MidnightUpdaterController.swift
  NoonMoaApt/Model/PushNotiController.swift
  NoonMoaApt/NoonMoaAptApp.swift
  NoonMoaApt/View/AptScene/EyeActive.swift
  NoonMoaApt/View/AptScene/EyeInactive.swift
  NoonMoaApt/View/AptScene/SceneButtons.swift
  NoonMoaApt/View/AptScene/SceneRoom.swift
  NoonMoaApt/View/AptView.swift
  NoonMoaApt/View/AttendanceCompletedView.swift
  NoonMoaApt/View/LoginView.swift
  NoonMoaApt/View/MainView.swift
  NoonMoaApt/View/OnboardingView.swift
Labels: Feat

#30 Feat/#24 구현 AttendanceView UI & 기능 구현
  NoonMoaApt.xcodeproj/project.pbxproj
  NoonMoaApt/Calendar/View/CalendarDayView.swift
  NoonMoaApt/Extension/Color+Extension.swift
  NoonMoaApt/View/AttendanceCompletedView.swift
  NoonMoaApt/View/AttendanceView.swift
  NoonMoaApt/View/CalendarScene/StampLargeView.swift
Labels: Feat, UI
